### ISSUE TITLE
PHP Notice right after activation

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#20] opened 2015-10-06 07:46 UTC
![image](https://cloud.githubusercontent.com/assets/1778633/10302759/0b8ecd2a-6c39-11e5-8c24-5aa07d0aa348.png)

**Comment by julien731** [comment] 2015-10-19 11:16
May have been fixed in master. Can't reproduce, to be verified.

**Closed** 2015-10-19 11:30 UTC
Labels: bug
